### ISSUE TITLE
Over-Restricting License

### ISSUE THREAD

**Issue by sirusdv** [uwsampa/grappa#209]
Due to the linked nature of the sample applications and header inclusions via grappa.hpp AGPLv1 viral licensing restricts any usage of grappa to exclusively open source programs.  

Please consider switching to AGPLv3 with Apache 2.0 licensed controller libraries that serialize through a socket to talk to the back-end. 

This is how MongoDB gets around this limitation while maintaining the open-sourceness of the core:
http://www.mongodb.org/about/licensing/

**Comment by bholt** [comment]
Grappa is now under a BSD license.
