### ISSUE TITLE
why use std::vector instead of std::map in GlobalHashMap code?

### ISSUE THREAD

**Issue by buaasun** [uwsampa/grappa#242]
I'm looking for some code which implement a global hash map. I found there is a `GlobalHashMap.hpp` in grappa system code, but I wonder why use `std::vector<Entry> entries` ,not `std::map<K,V>`. Is there any special consideration about this?

**Comment by bmyerz** [comment]
You are referring to https://github.com/uwsampa/grappa/blob/master/system/GlobalHashMap.hpp#L70.

The structure of `GlobalHashMap` is a [global array of Cells](https://github.com/uwsampa/grappa/blob/master/system/GlobalHashMap.hpp#L194), and each `Cell` is a list of keys that hash to that `Cell`.

**Comment by buaasun** [comment]
OK, I see..
