### ISSUE TITLE
How to send a big message?

### ISSUE THREAD

**Issue by buaasun** [uwsampa/grappa#243]
https://github.com/uwsampa/grappa/blob/master/system/Message.hpp#L318
In this line, I found payload size of PalyloadMessage is just a `int16_t`, Is there any way to send a big message which size may be about 10 KBs ?

**Comment by nelsonje** [comment]
int16_t is large enough to support up to 32KB, so you should be fine.

**Comment by buaasun** [comment]
how about more than 32KB, may be 1MB? Is there a away to send unlimited size of message?

**Comment by nelsonje** [comment]
Sure. But note that since Grappa's philosophy is to express fine-grained parallelism/communication and let the runtime do the large message formation, this API is less well-developed. I'm working on part of it in a separate branch right now.
