### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by rbarrett23** [uwsampa/grappa#272]
Folks,
Just pulled, and get this error:

% cd grappa/
% ./configure 
./configure:72: syntax error, unexpected kNOT
  if not(opt.cc) && not(opt.cxx)
                       ^
I'm using 
- gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
- cmake version 2.8.12.2
- openmpi-1.8-gnu 

What am I missing?

Thanks.

**Comment by bmyerz** [comment]
is your Ruby >= 1.9.3?

ruby -v

**Comment by rbarrett23** [comment]
Dang, figured I missed something: 

ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

Thanks.
