### ISSUE TITLE
Question about global_alloc

### ISSUE THREAD

**Issue by septicmk** [uwsampa/grappa#287]
I'm a Berkeley Unifiled Parallel C([UPC](http://upc.lbl.gov/)) user. now I'm trying to find a way to allocate global share memory like UPC does(something like `shared int z[x];`).

Assuming that I'm going to allocate an array that `length(array)=Grappa::cores()`, and i-th element in that array just reside in Core i. 

<pre>
|   core 0    |   core 1    |   core 2   |   core 3    |  
-----------------------------------------------------------  
|  array[0]   |  array[1]   |  array[2]  |  array[3]   |  
</pre>
If I use Linear addresses, data will not scatter on all cores, since `block_size=64`. 
If I use Symmetric addresses , I can't use `delegate::read()` to read value on other cores, since they all have the same name.

**Comment by bholt** [comment]
Since Grappa is still actually an SPMD execution, I'd probably allocate anything that needs to be on all cores as static globals. You can access a specific Core's version with a `delegate::call` I think. Something like:

~~~cpp
int z;

int sum() {
    int total = 0;
    for (Core i = 0; i < Grappa::cores(); i++) {
        total += delegate::call(i, []{ return z; });
    }
    return total;
}
~~~

(note, I didn't try to compile this)

**Comment by nelsonje** [comment]
You could also form a pointer to the specific version you want, like:

```
int z;

int sum() {
    int total = 0;
    for (Core i = 0; i < Grappa::cores(); i++) {
        total += delegate::read( make_global( &z, i ) );
    }
    return total;
}
```

(like brandon, did not try to compile this)

**Comment by septicmk** [comment]
It's so tricky, and I have to define the variable out side the `main`, but it does work, Thank you two. I think I can mark this question as closed...
