### ISSUE TITLE
applications/pagerank cannot run ?

### ISSUE THREAD

**Issue by guowentian** [uwsampa/grappa#292]
Hi, I understand there are two pagerank instances. The one in applications/pagerank cannot run, is it? When I compile it, I get compile error. Does it mean that you don't maintain this pagerank anymore ? If you still maintain it, any hint to solve the compile error ?

**Comment by nelsonje** [comment]
Sorry, we don't maintain any of Grappa anymore. 

But the pagerank implementation you want to use is the one in applications/graphlab/pagerank.cpp (not pagerank_new.cpp or applications/pagerank.cpp).
